// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqcHEFD4S8MK9zS6lKl9UVGGGRjnsbqXE',
    appId: '1:1040963148149:web:4b5dd103b7c59fa7bc5b3c',
    messagingSenderId: '1040963148149',
    projectId: 'isoclim25',
    authDomain: 'isoclim25.firebaseapp.com',
    storageBucket: 'isoclim25.appspot.com',
    measurementId: 'G-71E36L615D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaDE6tG75MtiGfWrFYZQDi2qMttdo0QRg',
    appId: '1:1040963148149:android:57f54960b31dba9fbc5b3c',
    messagingSenderId: '1040963148149',
    projectId: 'isoclim25',
    storageBucket: 'isoclim25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrUcCEe4uIqU0LNzaA52O0nhNOe6ycloY',
    appId: '1:1040963148149:ios:b5c8d715ac212aa6bc5b3c',
    messagingSenderId: '1040963148149',
    projectId: 'isoclim25',
    storageBucket: 'isoclim25.appspot.com',
    iosBundleId: 'com.example.isoclim25',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrUcCEe4uIqU0LNzaA52O0nhNOe6ycloY',
    appId: '1:1040963148149:ios:218df3934f1c5061bc5b3c',
    messagingSenderId: '1040963148149',
    projectId: 'isoclim25',
    storageBucket: 'isoclim25.appspot.com',
    iosBundleId: 'com.example.isoclim25.RunnerTests',
  );
}
